name: gic_flutter
description: Gaming Interface Client

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 5.4.3+26029884

environment:
  sdk: ">=3.5.0 <4.0.0"
  
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  #flutter_cupertino_localizations: ^1.0.1
  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6

  archive: ^3.3.8
  audioplayers: ^6.1.0
  device_info_plus: ^10.1.2
  equatable: ^2.0.3
  file_picker: ^8.0.7
  flutter_colorpicker: ^1.0.3
  flutter_email_sender: ^6.0.3
  flutter_linkify: ^6.0.0
  get_it: ^8.0.2
  http: ^1.2.2
  introduction_screen: ^3.1.11
  keep_screen_on: ^3.0.0
  package_info_plus: ^8.1.1
  path_provider: ^2.1.1
  permission_handler: ^11.3.1
  pointycastle: ^3.7.3
  rxdart: ^0.28.0
  scrollable_positioned_list: ^0.3.8
  #nullable scrollable_positioned_list: ^0.2.0-nullsafety.0
  share_plus: ^10.0.0
  shared_preferences: ^2.2.1  #'>=0.5.7+3 <2.0.0'
  #nullable shared_preferences: ^2.0.6
  showcaseview: ^3.0.0
  url_launcher: ^6.1.14
  gesture_x_detector:
    path: ../xgesture_flutter

  #intent: ^1.3.4
# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

dependency_overrides:
      win32: ^5.5.4
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/screens/
    - assets/images/icons/
    - assets/images/controls/
    - assets/audio/flick.wav

  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Lobster-Regular
       fonts:
         - asset: assets/fonts/Lobster-Regular.ttf
     - family: Nunito-Regular
       fonts:
         - asset: assets/fonts/Nunito-Regular.ttf
     - family: ShareTech-Regular
       fonts:
         - asset: assets/fonts/ShareTech-Regular.ttf
     - family: Righteous-Regular
       fonts:
         - asset: assets/fonts/Righteous-Regular.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
