name: gesture_x_detector
description: a lightweight gesture detector that supports multiple types(Tap, DoubleTap, Scale, Long-Press, Move) and all callbacks can be used simultaneously
version: 1.0.0
# author: Viet Nguyen <taodo2291@gmail.com>
homepage: https://github.com/taodo2291/xgesture_flutter

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
